#!/usr/bin/env rake -f
# -*- coding: utf-8 -*-
# File Name: `(buffer-name)`
# Description: 
# Reference: 
# Author: amoblin <amoblin@gmail.com>
# Created Time: `(format-time-string "%Y-%m-%d %a %H:%M")`

target :default do
  
end
